### ISSUE TITLE
WiFi implementation 

### ISSUE THREAD

**Issue by Lat9898** [stas-sl/esphome-sound-level-meter#12]
hey buddy 
I hope that u can maybe help me, everything is working fine but when i implement wifi somehow it is not working with freertos i get constantly this error: 
Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception).
Debug exception reason: Stack canary watchpoint triggered (Mic I2S Reader) 
Core  0 register dump:
PC      : 0x4008f75b  PS      : 0x00060736  A0      : 0x8008589a  A1      : 0x3ffe89c0
A2      : 0x3ffbf6b0  A3      : 0xb33fffff  A4      : 0x0000abab  A5      : 0x00060723  
A6      : 0x00060720  A7      : 0x0000cdcd  A8      : 0xb33fffff  A9      : 0xffffffff
A10     : 0x3ffe9230  A11     : 0x3ffb6884  A12     : 0x3ffb6af8  A13     : 0x00000042  
A14     : 0x007bf6b0  A15     : 0x003fffff  SAR     : 0x00000004  EXCCAUSE: 0x00000001
EXCVADDR: 0x00000000  LBEG    : 0x4008a505  LEND    : 0x4008a515  LCOUNT  : 0xfffffffa  
and her is my wifi code 
/*
  WiFi Connectivity Implementation

  This C++ file manages WiFi connectivity using the WiFi library and NeoPixel feedback.
  It includes functions to connect to WiFi networks, handle multiple network options, and indicate connection status.

  Purpose:
  - Connect to available WiFi networks using stored credentials.
  - Provide feedback using NeoPixel LEDs to indicate successful or failed WiFi connection attempts.

  Author: [Latif Faghiri]
*/

#include "Arduino.h"
#include "Wifi.h"

// Constructor 
MyWiFi::MyWiFi() : pixels(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800) {
  // Do Nothing 
}

// Getting Wifi
void MyWiFi::begin() {
  wifiMulti.addAP(WIFI_SSID1, WIFI_PASSWORD1);
  wifiMulti.addAP(WIFI_SSID2, WIFI_PASSWORD2);
}

// Connecting to Strongest Wifi
void MyWiFi::connect() {
  begin();
  Serial.print("Connecting: ");
  int WiFiAttempt = 0;
  int WiFiTimeout = 10;
  
  // Checking 
  while (WiFi.status() != WL_CONNECTED && WiFiAttempt < WiFiTimeout) {
    delay(100);
    Serial.println(".");
    WiFiAttempt++;
  }

  
  if (wifiMulti.run() == WL_CONNECTED) {
    Serial.print("\nSuccessfully Connected to: ");
    Serial.println(WiFi.SSID());
    Serial.println(" ");
    Serial.print("IP-Address: ");
    Serial.println(WiFi.localIP());

// Neopixel should light blue to confirm connection 
    for (int i = 0; i < 2; i++) {
      pixels.setPixelColor(0, pixels.Color(0, 0, 255));
      pixels.show();
      delay(500);
      pixels.clear();
      pixels.show();
      delay(500);
    }
  } else {
    Serial.println("Failed to establish WiFi connection");
    Serial.println("Please try again!!!!!!!"); 
  }
}

int MyWiFi::status(){
  return WiFi.status(); 
}

what do i do wrong

**Comment by stas-sl** [comment]
Sorry, this seems nothing to do with sound level meter component.
