### ISSUE TITLE
Add ability to enable/disable component updates dynamically via actions

### ISSUE THREAD

**Issue by Strophe27** [stas-sl/esphome-sound-level-meter#4]
Hi, thx a lot fort that !
I just use the dBA peak sensor for my needs, with a 0.1ms refresh time.
Is it possible to have a boolean switch to turn the sensor on/off, to avoid to send datas when I don't need ?
I don't know if it's possible in the yaml config ?

**Comment by stas-sl** [comment]
Hi, I've added `sound_level_meter.turn_on`, `sound_level_meter.turn_off`, `sound_level_meter.toggle` actions, you can use them with switch/binary_sensor in config (see example https://github.com/stas-sl/esphome-sound-level-meter/blob/main/advanced-example-config.yaml). Hope it will work for you.

**Comment by Strophe27** [comment]
Wow thanks a lot !! I will try and implement that next week.
